export const getPassportImage = (countryCode: string) => {
  return `https://flagcdn.com/${countryCode.toLowerCase()}.svg`;
};

export const countryCodeMap: { [key: string]: string } = {
  "Japan": "jp",
  "Singapore": "sg",
  "Germany": "de",
  "Spain": "es",
  "Finland": "fi",
  "Italy": "it",
  "Luxembourg": "lu",
  "Austria": "at",
  "Denmark": "dk",
  "Netherlands": "nl",
  "Sweden": "se",
  "France": "fr",
  "Ireland": "ie",
  "Portugal": "pt",
  "United Kingdom": "gb",
  "Belgium": "be",
  "Norway": "no",
  "Switzerland": "ch",
  "United States": "us",
  "Australia": "au",
  "Canada": "ca",
  "Czech Republic": "cz",
  "Greece": "gr",
  "Poland": "pl",
  "Hungary": "hu",
  "New Zealand": "nz",
  "Estonia": "ee",
  "Latvia": "lv",
  "Lithuania": "lt",
  "Slovakia": "sk",
  "Slovenia": "si",
  "Iceland": "is",
  "Malta": "mt",
  "South Korea": "kr",
  "China": "cn",
  "Thailand": "th",
  "Malaysia": "my",
  "UAE": "ae",
  "Brazil": "br",
  "Argentina": "ar",
  "Romania": "ro",
  "Bulgaria": "bg",
  "Croatia": "hr",
  "Cyprus": "cy",
  "Monaco": "mc",
  "Liechtenstein": "li",
  "Brunei": "bn",
  "Hong Kong": "hk",
  "Taiwan": "tw",
  "Macau": "mo",
  "Mongolia": "mn",
  "Cambodia": "kh",
  "Laos": "la",
  "Myanmar": "mm",
  "Nepal": "np",
  "Bangladesh": "bd",
  "Sri Lanka": "lk",
  "Maldives": "mv",
  "Bahrain": "bh",
  "Jordan": "jo",
  "Lebanon": "lb",
  "Iran": "ir",
  "Iraq": "iq",
  "Yemen": "ye",
  "Syria": "sy",
  "Israel": "il",
  "Turkey": "tr",
  "Russia": "ru",
  "Ukraine": "ua",
  "Belarus": "by",
  "Moldova": "md",
  "Georgia": "ge",
  "Armenia": "am",
  "Azerbaijan": "az",
  "Kazakhstan": "kz",
  "Uzbekistan": "uz",
  "Turkmenistan": "tm",
  "Kyrgyzstan": "kg",
  "Tajikistan": "tj",
  "Afghanistan": "af",
  "Pakistan": "pk",
  "India": "in",
  "South Africa": "za",
  "Nigeria": "ng",
  "Kenya": "ke",
  "Egypt": "eg",
  "Morocco": "ma",
  "Tunisia": "tn",
  "Algeria": "dz",
  "Libya": "ly",
  "Sudan": "sd",
  "Ethiopia": "et",
  "Somalia": "so",
  "Mexico": "mx",
  "Cuba": "cu",
  "Jamaica": "jm",
  "Haiti": "ht",
  "Dominican Republic": "do",
  "Panama": "pa",
  "Costa Rica": "cr",
  "Colombia": "co",
  "Venezuela": "ve",
  "Peru": "pe",
  "Chile": "cl",
  "Uruguay": "uy",
  "Paraguay": "py",
  "Bolivia": "bo",
  "Ecuador": "ec",
  // Add more country codes as needed
}; 